import os
from dotenv import load_dotenv # type: ignore


load_dotenv()


WB_API_KEY_OLTEX = os.getenv("WB_API_KEY_OLTEX")
WB_API_KEY_WELLINA = os.getenv("WB_API_KEY_WELLINA")
WB_API_KEY_MIOTEX = os.getenv("WB_API_KEY_MIOTEX")
WB_API_KEY_IE_STEGNO = os.getenv("WB_API_KEY_IE_STEGNO")

WB_API_CONF_LIST_MAP = [
    {"PA": "OLTEX", "API_KEY": WB_API_KEY_OLTEX},
    {"PA": "WELLINA", "API_KEY": WB_API_KEY_WELLINA},
    {"PA": "MIOTEX", "API_KEY": WB_API_KEY_MIOTEX},
    {"PA": "IE_STEGNO", "API_KEY": WB_API_KEY_IE_STEGNO}
]


OZON_API_KEY_OLTEX = os.getenv("OZON_API_KEY_OLTEX")
OZON_API_KEY_WELLINA = os.getenv("OZON_API_KEY_WELLINA")
OZON_API_KEY_MIOTEX = os.getenv("OZON_API_KEY_MIOTEX")
OZON_API_KEY_WISTROVA = os.getenv("OZON_API_KEY_WISTROVA")
OZON_API_KEY_IE_STEGNO = os.getenv("OZON_API_KEY_IE_STEGNO")

OZON_CLIENT_ID_OLTEX = os.getenv("OZON_CLIENT_ID_OLTEX")
OZON_CLIENT_ID_WELLINA = os.getenv("OZON_CLIENT_ID_WELLINA")
OZON_CLIENT_ID_MIOTEX = os.getenv("OZON_CLIENT_ID_MIOTEX")
OZON_CLIENT_ID_WISTROVA = os.getenv("OZON_CLIENT_ID_WISTROVA")
OZON_CLIENT_ID_IE_STEGNO = os.getenv("OZON_CLIENT_ID_IE_STEGNO")

OZON_API_CONF_LIST_MAP = [
    {"PA": "OLTEX", "API_KEY": OZON_API_KEY_OLTEX, "CLIENT_ID": OZON_CLIENT_ID_OLTEX},
    {"PA": "WELLINA", "API_KEY": OZON_API_KEY_WELLINA, "CLIENT_ID": OZON_CLIENT_ID_WELLINA},
    {"PA": "MIOTEX", "API_KEY": OZON_API_KEY_MIOTEX, "CLIENT_ID": OZON_CLIENT_ID_MIOTEX},
    {"PA": "WISTROVA", "API_KEY": OZON_API_KEY_WISTROVA, "CLIENT_ID": OZON_CLIENT_ID_WISTROVA},
    {"PA": "IE_STEGNO", "API_KEY": OZON_API_KEY_IE_STEGNO, "CLIENT_ID": OZON_CLIENT_ID_IE_STEGNO}
]


YANDEX_API_KEY_OLTEX = os.getenv("YANDEX_API_KEY_OLTEX")
YANDEX_API_KEY_WELLINA = os.getenv("YANDEX_API_KEY_WELLINA")
YANDEX_API_KEY_MIOTEX = os.getenv("YANDEX_API_KEY_MIOTEX")
YANDEX_API_KEY_WISTROVA = os.getenv("YANDEX_API_KEY_WISTROVA")

YANDEX_API_CAMPAIGN_ID_OLTEX = os.getenv("YANDEX_API_CAMPAIGN_ID_OLTEX")
YANDEX_API_CAMPAIGN_ID_WELLINA = os.getenv("YANDEX_API_CAMPAIGN_ID_WELLINA")
YANDEX_API_CAMPAIGN_ID_MIOTEX = os.getenv("YANDEX_API_CAMPAIGN_ID_MIOTEX")
YANDEX_API_CAMPAIGN_ID_WISTROVA = os.getenv("YANDEX_API_CAMPAIGN_ID_WISTROVA")

YANDEX_API_BUSINESS_ID_OLTEX = os.getenv("YANDEX_API_BUSINESS_ID_OLTEX")
YANDEX_API_BUSINESS_ID_WELLINA = os.getenv("YANDEX_API_BUSINESS_ID_WELLINA")
YANDEX_API_BUSINESS_ID_MIOTEX = os.getenv("YANDEX_API_BUSINESS_ID_MIOTEX")
YANDEX_API_BUSINESS_ID_WISTROVA = os.getenv("YANDEX_API_BUSINESS_ID_WISTROVA")

YANDEX_API_CONF_LIST_MAP = [
    {"PA": "OLTEX", "API_KEY": YANDEX_API_KEY_OLTEX, "CAMPAIGN_ID": YANDEX_API_CAMPAIGN_ID_OLTEX, "BUSINESS_ID": YANDEX_API_BUSINESS_ID_OLTEX},
    {"PA": "WELLINA", "API_KEY": YANDEX_API_KEY_WELLINA, "CAMPAIGN_ID": YANDEX_API_CAMPAIGN_ID_WELLINA, "BUSINESS_ID": YANDEX_API_BUSINESS_ID_WELLINA},
    {"PA": "MIOTEX", "API_KEY": YANDEX_API_KEY_MIOTEX, "CAMPAIGN_ID": YANDEX_API_CAMPAIGN_ID_MIOTEX, "BUSINESS_ID": YANDEX_API_BUSINESS_ID_MIOTEX},
    {"PA": "WISTROVA", "API_KEY": YANDEX_API_KEY_WISTROVA, "CAMPAIGN_ID": YANDEX_API_CAMPAIGN_ID_WISTROVA, "BUSINESS_ID": YANDEX_API_BUSINESS_ID_WISTROVA}
]
